###服务启动端口号
server:
  port: 8021
###服务名称(服务注册到eureka名称)  
spring:
    application:
        name: app-zhoufeng-order
###服务注册到eureka地址
eureka:
  client:
    service-url:
           defaultZone: http://localhost:8100/eureka

           
###因为该应用为注册中心，不会注册自己
    register-with-eureka: true
###是否需要从eureka上获取注册信息
    fetch-registry: true
###设置feign客户端超时时间
###SpringCloud feign 默认开启支持ribbon
ribbon:
###指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间。
 ReadTimeout: 5000
###指的是建立连接后从服务器读取到可用资源所用的时间。 
 ConnectTimeout: 5000
 
###开启Hystrix断路器 
feign:
  hystrix:
    enabled: true


#### hystrix禁止服务超时时间
#hystrix:  
# command: 
#   default: 
#      execution: 
#       timeout: 
#        enabled: false

###建议 hystrix服务超时时间大致5-10  如果产生业务延迟比较长 建议使用mq 或者异步请求
hystrix:
  command: 
   default: 
    execution: 
    isolation:
     thread: 
     timeoutInMilliseconds: 5000

    
 